version: "3.4"

services:
  database:
    build: ./mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: amazon
    ports:
      - 3306:3306
    volumes:
      - ./share/data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
    restart: always

  chrome:
    image: selenium/standalone-chrome:4.0.0-beta-3-prerelease-20210321
    container_name: amz-chrome
    volumes:
      - /dev/shm:/dev/shm
    environment:
      SE_NODE_MAX_SESSIONS: 8
    ports:
      - 4444:4444
    restart: always

  amz-backend:
    build: ./amz-backend
    container_name: amz-backend
    environment:
      MYSQL_DATABASE: amazon
      MYSQL_HOST: database
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      SELENIUM_DOMAIN: chrome
      CORE_POOL_SIZE: 2
      MAX_POOL_SIZE: 1000
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - database
      - chrome

  amz-frontend:
    build: ./amz-frontend
    container_name: amz-frontend
    ports:
      - 9000:8080
    restart: always
    depends_on:
      - amz-backend
